# -*- coding: utf-8 -*-
"""MetodoBisseçao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19If-iV-Nyee3x_0fPh0hPnUysZrd5i4C
"""

import numpy as np

def f(x):
  # definição da função dada
  y = x**3 - 9*x + 3
  return y

a = float(input("Entre com o valor de a: "))
b = float(input("Entre com o valor de b: "))
tol = float(input("Defina uma tolerancia: "))

x = (a+b)/2

n = 0
while abs(f(x)) > tol:

  x = (a+b)/2

  print(n, a, x, b, f(a), f(x), f(b))

  if f(a)*f(x) < 0:
    a = a
    b = x
  elif f(b)*f(x) < 0:
    b = b
    a = x
  n += 1

print("A raiz é", x)

